name: First CI/CD

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Merge test into main
        run: |
          git config --global user.name "dhruvthak3r"
          git config --global user.email "dhruvthaker777@gmail.com"
          git checkout -b main origin/main
          git pull origin main
          git merge test --no-ff -m "Merge test branch into main"
          git push origin main

  image:
    needs: merge
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Re-build and Push Image
        run: |
          docker build -t dhruvthak3r/chatbot:latest .
          docker push dhruvthak3r/chatbot:latest

  deploy:
    needs: image
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli
          gcloud --version

      - name: Configure gcloud CLI
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          gcloud config set project loyal-throne-448413-c8

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatbot \
            --image=dhruvthak3r/chatbot:latest \
            --platform=managed \
            --region=asia-south1 \
            --allow-unauthenticated
