name: First CI/CD

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest-asyncio 
        

      - name: Run tests
        run: pytest -v
      
      - name: merge into main
        if: success()
        run : |
          git fetch --all
          git commit -a -m "please work"
          git checkout main
          git pull origin main
          git merge test --allow-unrelated-histories
          git push origin main